apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-mod-cache
  namespace: ci
spec:
  resources:
    requests:
      storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: itsuki
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kefka-build-test
  namespace: ci

spec:
  description: |
    The CI pass for Kefka including Go tests and linting.
  params:
    - name: repo-url
      type: string
      description: "Git repo to clone"
      default: "https://tangled.org/xeiaso.net/kefka"
    - name: "commit"
      type: string
      description: "Git revision to check out"
  workspaces:
    - name: repo-data
      description: |
        Cloned repo files.
    - name: go-mod-cache
      description: |
        Go module cache
  tasks:
    - name: clone-repo
      taskSpec:
        params:
          - name: "url"
            description: "repository URL to clone"
          - name: "commit"
            description: "repository commit to check out"
        steps:
          - name: git-clone
            image: reg.xeiaso.net/xe/x/git:latest
            script: |
              set -euo pipefail
              git clone $(params.url) /workspace/repo-data/repo
              cd /workspace/repo-data/repo
              git checkout $(params.commit)
        workspaces:
          - name: "repo-data"
            description: "Repository data for other steps in the pipeline"
            mountPath: "/workspace/repo-data"
      workspaces:
        - name: repo-data
          workspace: repo-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: commit
          value: $(params.commit)
    - name: go-test
      runAfter: ["clone-repo"]
      taskSpec:
        params:
          - name: "folder"
            description: "path to source code"
            default: "/workspace/repo-data/repo"
        steps:
          - name: run-tests
            image: golang:1.26
            workingDir: $(params.folder)
            env:
              - name: "GOPATH"
                value: "/go"
            script: |
              go test ./...
        workspaces:
          - name: "repo-data"
            description: "Repository data for other steps in the pipeline"
            mountPath: "/workspace/repo-data"
          - name: "go-mod-cache"
            description: "Go module cache"
            mountPath: "/go"
      workspaces:
        - name: repo-data
          workspace: repo-data
        - name: go-mod-cache
          workspace: go-mod-cache
