apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kefka-build-test
  namespace: ci

spec:
  description: |
    The CI pass for Kefka including Go tests and linting.
  params:
    - name: repo-url
      type: string
      description: "Git repo to clone"
      default: "https://tangled.org/xeiaso.net/kefka"
    - name: "commit"
      type: string
      description: "Git revision to check out"
  workspaces:
    - name: repo-data
      description: |
        Cloned repo files.
    - name: go-mod-cache
      description: |
        Go module cache
  tasks:
    - name: fix-permissions-repo-data
      taskRef:
        name: fix-permissions
      workspaces:
        - name: dir
          workspace: repo-data
      params:
        - name: uid
          value: 65532
        - name: gid
          value: 65532
    - name: clone-repo
      runAfter: ["fix-permissions-repo-data"]
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: repo-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.commit)
        - name: subdirectory
          value: repo
    - name: go-test
      runAfter: ["clone-repo"]
      taskSpec:
        params:
          - name: "folder"
            description: "path to source code"
            default: "/workspace/repo-data/repo"
        steps:
          - name: run-tests
            image: golang:1.26
            workingDir: $(params.folder)
            env:
              - name: "GOPATH"
                value: "/go"
            script: |
              go test ./...
        workspaces:
          - name: "repo-data"
            description: "Repository data for other steps in the pipeline"
            mountPath: "/workspace/repo-data"
          - name: "go-mod-cache"
            description: "Go module cache"
            mountPath: "/go"
      workspaces:
        - name: repo-data
          workspace: repo-data
        - name: go-mod-cache
          workspace: go-mod-cache
    - name: docker-build
      runAfter: ["clone-repo"]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: repo-data
      params:
        - name: IMAGE
          value: registry.int.xeserv.us/xeiaso.net/kefka/sophia:latest
        - name: CONTEXT
          value: repo
        - name: DOCKERFILE
          value: ./docker/sophia.Dockerfile
