apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: tigris-creds
  labels:
    app.kubernetes.io/name: sophia
spec:
  itemPath: "vaults/Kubernetes/items/Sophia Tigris creds"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: sophia-ssh-keys
  labels:
    app.kubernetes.io/name: sophia
spec:
  itemPath: "vaults/Kubernetes/items/Sophia SSH Keys"
