apiVersion: v1
kind: Service
metadata:
  name: sophia
  labels:
    app.kubernetes.io/name: sophia
  annotations:
    service.beta.kubernetes.io/vultr-loadbalancer-protocol: tcp
    service.beta.kubernetes.io/vultr-loadbalancer-label: sophia.xeiaso.net
    service.beta.kubernetes.io/vultr-loadbalancer-hostname: sophia.xeiaso.net
spec:
  selector:
    app.kubernetes.io/name: sophia
  ports:
    - port: 22
      targetPort: 2222
      name: ssh
  type: LoadBalancer
